### ISSUE TITLE
What does osmada do?

### ISSUE THREAD

**Issue by joostschouppe** [Cartocite/osmada#17]
Hi,
I know this is common on Github projects, but could you please add a section to the readme explaining what the tool is and does exactly? Or provide a link to other documentation about the project?

**Comment by naomap** [comment]
Sure, will do that later this week. 
In short, OSMADA can analyze the result of Overpass Augmented Diff queries, apply filters (trusted users, minor changes...), and export them in the same or a different format.

**Comment by naomap** [comment]
Ive added an introduction section to the README.
