### ISSUE TITLE
Allow multi-filter for main tag selection

### ISSUE THREAD

**Issue by JocelynDelalande** [Cartocite/osmada#3]
Currently, main tags configuration is defined as follows:

    TAGS_IMPORTANCE = ['railway=*', 'shop=*']

We would like to be able to define them with multiple filters, like:

    TAGS_IMPORTANCE = ['railway=*,operator=SNCF', 'shop=*']

**Comment by JocelynDelalande** [comment]
@charlesmillet @naomap @Stefal  if I have that configuration:

    TAGS_IMPORTANCE = ['railway=*', 'shop=*']

And I found a match on `railway=station`, what would be best:

- return `railway=station` as main tag
- return `railway=*` as main tag

?

**Comment by naomap** [comment]
I would say it is best to return `railway=station `as it does now : this contains more information.

**Comment by JocelynDelalande** [comment]
Ok, so let's change nothing :-)
