### ISSUE TITLE
Add an IGNORED_KEYS blacklist

### ISSUE THREAD

**Issue by JocelynDelalande** [Cartocite/osmada#6]
Ability to delete changes implying *only* tags from a settings-specified blacklist.

Example setting:

```
IGNORED_TAGS=['source', 'note']
```

If a change relates only to tags listed within `IGNORED_TAGS`, then drop it from the output.

**Comment by JocelynDelalande** [comment]
@charlesmillet @Stefal I need more information: what is the goal:

1. totally remove those tags from the osmada data (that means no trace of them, they get deleted from osmada internal database). Thus, output reports will never show them.
2. just use them as an exclusion filter: they will still be present in reports (added_tags/removed_tags...), but the actions involving *only* ignored tags will be removed from the output

If it does not matter a lot, I'd go for 1. because 2. has a longer execution time.

**Comment by naomap** [comment]
I'd go d'or option 1 : if we decide to ignore a tag we dont want our review process to be diverted by this tag.

**Comment by JocelynDelalande** [comment]
At the end… As I found a way to do it without hitting performances (+1.5% runtime).
**I finally went for option 2**, in order to be more conservative and avoid destroying data (which makes it impossible for other filters to use them).

We could, if required in future, do a cosmetic change to remove those tags from the output.
